/**
 * Next-Gen App API
 * Die REST Web-Schnittstelle zu der Next-Gen App Anwendung
 *
 * The version of the OpenAPI document: v1
 * Contact: info@brunnerinformatik.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Diese Klasse reprÃ¤sentiert ein Data-Transfer-Object einer Adresse.
 */
export interface AdresseDTO { 
    /**
     * Diese Eigenschaft ruft die System.Guid des Mandanten ab, in welchem sich diese Adresse befindet, oder  setzt diese.
     */
    mandant?: string;
    /**
     * Diese Eigenschaft ruft die System.Guid der Holding ab, welche diese Eindeutig innerhalb des Next-Gen  Projektes identifiziert, oder setzt diese.
     */
    guid?: string | null;
    /**
     * Kurzer Anzeigetext
     */
    stichwort?: string | null;
    /**
     * Erster Teil des Namens (Vorname, Firmenname, etc.)
     */
    name1?: string | null;
    /**
     * Zweiter Teil des Namens (Nachname, Firmenart, etc.)
     */
    name2?: string | null;
    /**
     * Erste Zeile der Adresse
     */
    adresse1?: string | null;
    /**
     * Zweite Zeile der Adresse
     */
    adresse2?: string | null;
    /**
     * Postleitzahl
     */
    plz?: string | null;
    /**
     * Postort der Adresse
     */
    ort?: string | null;
    /**
     * E-Mail Adresse
     */
    eMail?: string | null;
    /**
     * Die Telefon-Nummer (Mobil oder Festnetz)
     */
    telefon?: string | null;
    /**
     * Diese Eigenschaft ruft den UTC Zeitstempel ab, wann diese Holding erstellt/erfasst wurde, oder setzt diesen.
     */
    creaDate?: string | null;
    /**
     * Diese Eigenschaft ruft die IdentitÃ¤t des Benutzers ab, welcher diese Holding erstellt/erfasst wurde, oder setzt  diese.
     */
    creaUser?: string | null;
    /**
     * Diese Eigenschaft ruft den UTC Zeitstempel ab, wann diese Holding zuletzt modifiziert/verÃ¤ndert wurde, oder  setzt diesen.
     */
    modDate?: string | null;
    /**
     * Diese Eigenschaft ruft die IdentitÃ¤t des Benutzers ab, welcher diese Holding zuletzt modifiziert/verÃ¤ndert hat,  oder setzt diese.
     */
    modUser?: string | null;
}

