/**
 * Next-Gen App API
 * Die REST Web-Schnittstelle zu der Next-Gen App Anwendung
 *
 * The version of the OpenAPI document: v1
 * Contact: info@brunnerinformatik.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EFormularDTO } from './eFormularDTO';


/**
 * Diese Klasse reprÃ¤sentiert ein Data-Transfer-Object fÃ¼r Elektro-Aktionen EntitÃ¤ten.
 */
export interface EAktionDTO { 
    /**
     * PrimÃ¤rschlÃ¼ssel: GUID des Mandanten.
     */
    mandant: string;
    /**
     * GUID der Elektro-Aktion.
     */
    guid?: string | null;
    /**
     * Bezeichnung dieser Elektro-Aktion.
     */
    bezeichnung?: string | null;
    /**
     * Wann die Aktion ausgefÃ¼hrt wurde.
     */
    ausgefuehrt?: string | null;
    /**
     * Aktionsdefinition, FremdschlÃ¼ssel zu AktionDef.
     */
    iD_AktionDef?: number | null;
    /**
     * GUID der Aktionsdefinition.
     */
    guiD_AktionDef?: string | null;
    /**
     * Frist der Aktion.
     */
    frist?: string | null;
    /**
     * Die GUID der Elektro-Leistung, zu welcher diese Elektro-Aktion gehÃ¶rt.
     */
    leistung?: string;
    /**
     * 1 = EigentÃ¼mer; 2 = Verwaltung; 4 = Stromkunde; 16 = StrombezÃ¼ger; 64 = Installateur; 128 = Kontrolleur; 512 = Auftraggeber.
     */
    verrechAn?: number | null;
    /**
     * ID des Dokumentes, auf welchem die AufwÃ¤nde verrechnet sind.
     */
    iD_RechDok?: number | null;
    /**
     * Erste Bemerkungszeile.
     */
    bemerkung?: string | null;
    /**
     * Zweite Bemerkungszeile.
     */
    bemerkung2?: string | null;
    /**
     * 0/leer = User; 4 = ohne Ausl.; 6 = mit Ausl.; 7 = User
     */
    geschEintrag?: number | null;
    /**
     * Die GUID der Formular-/Dokumentkategorie.
     */
    dokumentKategorie?: string;
    dokument?: EFormularDTO;
}

