/**
 * Next-Gen App API
 * Die REST Web-Schnittstelle zu der Next-Gen App Anwendung
 *
 * The version of the OpenAPI document: v1
 * Contact: info@brunnerinformatik.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Diese Klasse reprÃ¤sentiert ein Data-Transfer-Object fÃ¼r Elektro-Anlagen EntitÃ¤ten.
 */
export interface EAnlageDTO { 
    /**
     * PrimÃ¤rschlÃ¼ssel: GUID des Mandanten.
     */
    mandant: string;
    /**
     * GUID der Elektro-Anlage.
     */
    guid?: string | null;
    /**
     * Elektro-Anlagennummer.
     */
    nummer?: string | null;
    /**
     * EidgenÃ¶ssischer Wohnungsidentifikator.
     */
    ewid?: number | null;
    /**
     * Bezeichnung des GebÃ¤udeteils (z.B.: \"1.OG links\").
     */
    gebaeudeTeil?: string | null;
    /**
     * Bezeichnung der Elektro-Anlage(z.B.: \"Wohnung\", \"Heizung\", \"Coiffeursalon\").
     */
    bezeichnung?: string | null;
    /**
     * TODO: Feldbeschreibung hinzufÃ¼gen (EAnlagen->RegistriertBei)!
     */
    registriertBei?: string | null;
    /**
     * Kontroll-Turnus in Jahren.
     */
    turnusJahre?: number | null;
    /**
     * Messpunkt gemÃ¤ss internationaler Bezeichnung.
     */
    messpunkt?: string | null;
    /**
     * Enddatum der GÃ¼ltigkeit dieser Elektro-Anlage.
     */
    gueltigBis?: string | null;
    /**
     * Bemerkungen zur Elektro-Anlage.
     */
    bemerkungen?: string | null;
    /**
     * Die GUID des GebÃ¤udes zu welchem diese Anlage gehÃ¶rt.
     */
    gebaeude?: string;
    /**
     * Inhaber, FremdschlÃ¼ssel auf \'GeschPartner\', Ã¼bersteuert Inhaber des referenzierten GebÃ¤udes.
     */
    iD_Inhaber?: number | null;
    /**
     * Stromkunde, FremdschlÃ¼ssel auf GeschPartner (FrÃ¼her: RechnungsempfÃ¤nger).
     */
    iD_Stromkunde?: number | null;
    /**
     * BezÃ¼ger, FremdschlÃ¼ssel auf GeschPartner wenn nicht der Stromkunde.
     */
    iD_Bezueger?: number | null;
    /**
     * Referenz-Nummer fÃ¼r externen Datenabgleich/DatenÃ¼bernahme/Datenaustausch.
     */
    referenzNr?: string | null;
    /**
     * true = Inhaber erhÃ¤lt keinen Abschaltbrief.
     */
    keinAbschAvisInh?: boolean | null;
    /**
     * true = Stromkunde erhÃ¤lt keinen Abschaltbrief (FrÃ¼her: KeinAbschAvisRepf).
     */
    keinAbschAvisStk?: boolean | null;
    /**
     * true = BezÃ¼ger erhÃ¤lt keinen Abschaltbrief.
     */
    keinAbschAvisBez?: boolean | null;
    /**
     * Nummer des ersten ZÃ¤hlers.
     */
    zaehlerNr1?: string | null;
    /**
     * Tarif fÃ¼r den ersten ZÃ¤hler.
     */
    tarif1?: string | null;
    /**
     * Nummer des zweiten ZÃ¤hlers.
     */
    zaehlerNr2?: string | null;
    /**
     * Tarif fÃ¼r den zweiten ZÃ¤hler.
     */
    tarif2?: string | null;
    /**
     * Nummer des dritten ZÃ¤hlers.
     */
    zaehlerNr3?: string | null;
    /**
     * Tarif fÃ¼r den dritten ZÃ¤hler.
     */
    tarif3?: string | null;
    /**
     * Die Art, wie die ZÃ¤hler ausgelesen werden.
     */
    ausleseArt?: string | null;
    /**
     * Der Ort, wo die ZÃ¤hler ausgelesen werden.
     */
    ausleseOrt?: string | null;
    /**
     * TODO: Feldbeschreibung hinzufÃ¼gen (EAnlagen->SicherungBez)!
     */
    sicherungBez?: string | null;
    /**
     * TODO: Feldbeschreibung hinzufÃ¼gen (EAnlagen->VerteilungNr)!
     */
    verteilungNr?: string | null;
    /**
     * TODO: Feldbeschreibung hinzufÃ¼gen (EAnlagen->FeldNr)!
     */
    feldNr?: string | null;
    /**
     * TODO: Feldbeschreibung hinzufÃ¼gen (EAnlagen->SicherungNr)!
     */
    sicherungNr?: string | null;
    /**
     * TODO: Feldbeschreibung hinzufÃ¼gen (EAnlagen->Sicherung)!
     */
    sicherung?: string | null;
    /**
     * TODO: Feldbeschreibung hinzufÃ¼gen (EAnlagen->SicherungsTyp)!
     */
    sicherungsTyp?: string | null;
    /**
     * TODO: Feldbeschreibung hinzufÃ¼gen (EAnlagen->Ausloesung)!
     */
    ausloesung?: string | null;
    /**
     * TODO: Feldbeschreibung hinzufÃ¼gen (EAnlagen->LeiterTyp)!
     */
    leiterTyp?: string | null;
    /**
     * TODO: Feldbeschreibung hinzufÃ¼gen (EAnlagen->LeitQuersch)!
     */
    leitQuersch?: string | null;
    /**
     * TODO: Feldbeschreibung hinzufÃ¼gen (EAnlagen->Erderart)!
     */
    erderart?: string | null;
    /**
     * TODO: Feldbeschreibung hinzufÃ¼gen (EAnlagen->ErdleiterQuersch)!
     */
    erdleiterQuersch?: string | null;
    /**
     * TODO: Feldbeschreibung hinzufÃ¼gen (EAnlagen->Erderart2)!
     */
    erderart2?: string | null;
    /**
     * TODO: Feldbeschreibung hinzufÃ¼gen (EAnlagen->ErdleiterQuersch2)!
     */
    erdleiterQuersch2?: string | null;
    /**
     * TODO: Feldbeschreibung hinzufÃ¼gen (EAnlagen->Erderart3)!
     */
    erderart3?: string | null;
    /**
     * TODO: Feldbeschreibung hinzufÃ¼gen (EAnlagen->ErdleiterQuersch3)!
     */
    erdleiterQuersch3?: string | null;
    /**
     * TODO: Feldbeschreibung hinzufÃ¼gen (EAnlagen->Erderart4)!
     */
    erderart4?: string | null;
    /**
     * TODO: Feldbeschreibung hinzufÃ¼gen (EAnlagen->ErdleiterQuersch4)!
     */
    erdleiterQuersch4?: string | null;
    /**
     * TODO: Feldbeschreibung hinzufÃ¼gen (EAnlagen->PotAusg)!
     */
    potAusg?: string | null;
    /**
     * TODO: Feldbeschreibung hinzufÃ¼gen (EAnlagen->PotAusgQuersch)!
     */
    potAusgQuersch?: string | null;
    /**
     * TODO: Feldbeschreibung hinzufÃ¼gen (EAnlagen->PotAusg2)!
     */
    potAusg2?: string | null;
    /**
     * TODO: Feldbeschreibung hinzufÃ¼gen (EAnlagen->PotAusgQuersch2)!
     */
    potAusgQuersch2?: string | null;
    /**
     * TODO: Feldbeschreibung hinzufÃ¼gen (EAnlagen->PotAusg3)!
     */
    potAusg3?: string | null;
    /**
     * TODO: Feldbeschreibung hinzufÃ¼gen (EAnlagen->PotAusgQuersch3)!
     */
    potAusgQuersch3?: string | null;
    /**
     * TODO: Feldbeschreibung hinzufÃ¼gen (EAnlagen->Schutzart)!
     */
    schutzart?: string | null;
    /**
     * TODO: Feldbeschreibung hinzufÃ¼gen (EAnlagen->FI)!
     */
    fi?: string | null;
    /**
     * TODO: Feldbeschreibung hinzufÃ¼gen (EAnlagen->Blitzschutz)!
     */
    blitzschutz?: boolean | null;
    /**
     * TODO: Feldbeschreibung hinzufÃ¼gen (EAnlagen->SicherungBemerk)!
     */
    sicherungBemerk?: string | null;
    /**
     * IK L-PE Anfang.
     */
    ik?: string | null;
    /**
     * IK L-N Anfang.
     */
    ikLN?: string | null;
    /**
     * IK L-PE Ende.
     */
    minIk?: string | null;
    /**
     * IK L-N Ende.
     */
    minIkLN?: string | null;
    /**
     * TODO: Feldbeschreibung hinzufÃ¼gen (EAnlagen->StandortMinIk)!
     */
    standortMinIk?: string | null;
    /**
     * TODO: Feldbeschreibung hinzufÃ¼gen (EAnlagen->RIso)!
     */
    rIso?: string | null;
    /**
     * TODO: Feldbeschreibung hinzufÃ¼gen (EAnlagen->ILeck)!
     */
    iLeck?: string | null;
    /**
     * TODO: Feldbeschreibung hinzufÃ¼gen (EAnlagen->Messgeraet)!
     */
    messgeraet?: string | null;
    /**
     * TODO: Feldbeschreibung hinzufÃ¼gen (EAnlagen->MessDatum)!
     */
    messDatum?: string | null;
    /**
     * TODO: Feldbeschreibung hinzufÃ¼gen (EAnlagen->MessName)!
     */
    messName?: string | null;
    /**
     * TODO: Feldbeschreibung hinzufÃ¼gen (EAnlagen->SchutzErfuellt)!
     */
    schutzErfuellt?: boolean | null;
    /**
     * true = Der Name des Stromkunden ist im Feld StromkName,  false = Der Stromkunde ist im Feld ID_Stromkunde
     */
    stromkNurName?: boolean | null;
    /**
     * Name des Stromkunden, falls StromkNurName = true ist.
     */
    stromkName?: string | null;
}

