/**
 * Next-Gen App API
 * Die REST Web-Schnittstelle zu der Next-Gen App Anwendung
 *
 * The version of the OpenAPI document: v1
 * Contact: info@brunnerinformatik.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Diese Klasse reprÃ¤sentiert ein Data-Transfer-Object fÃ¼r Elektro-AuftrÃ¤ge Doumentenpool EntitÃ¤ten.
 */
export interface EAuftragDokumentPoolDTO { 
    /**
     * GUID des Mandanten.
     */
    mandant?: string;
    /**
     * GUID des Elektro-Auftrag.
     */
    guidAuftrag?: string | null;
    /**
     * GUID der Beilage.
     */
    guidBeilage?: string | null;
}

