/**
 * Next-Gen App API
 * Die REST Web-Schnittstelle zu der Next-Gen App Anwendung
 *
 * The version of the OpenAPI document: v1
 * Contact: info@brunnerinformatik.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EAuftragDokumentDTO } from './eAuftragDokumentDTO';
import { EAuftragPhaseDTO } from './eAuftragPhaseDTO';


/**
 * Diese Klasse reprÃ¤sentiert ein Data-Transfer-Object fÃ¼r Elektro-AuftrÃ¤ge EntitÃ¤ten.
 */
export interface EAuftragDTO { 
    /**
     * PrimÃ¤rschlÃ¼ssel: GUID des Mandanten.
     */
    mandant: string;
    /**
     * GUID des Elektro-Auftrag.
     */
    guid?: string | null;
    /**
     * 0, leer = Nichts, 1 = exportiert, (2 = re-importiert).
     */
    exportStatus?: number | null;
    /**
     * GUID fÃ¼r Dossier-Export und -Synchronisation.
     */
    exportGUID?: string | null;
    /**
     * Auftragsnummer vergeben vom Anwender.
     */
    auftragsNr: string;
    /**
     * Internes Stichwort fÃ¼r Ausdruck auf Formularen.
     */
    stichwort?: string | null;
    /**
     * Auftragskategorie.
     */
    kategorie?: string | null;
    /**
     * Verrechnungsadresse des Auftraggebers, FremdschlÃ¼ssel auf GeschPartner.
     */
    iD_RechAddr?: number | null;
    /**
     * Verrechnungsadresse, FremdschlÃ¼ssel auf GeschPartner.
     */
    iD_RechAdrGP?: number | null;
    /**
     * Auftrags-Vermittler / ProvisionsempfÃ¤nger, FremdschlÃ¼ssel auf GeschPartner.
     */
    iD_VermittlerGP?: number | null;
    /**
     * Kostenstelle 1.
     */
    habenKst1?: string | null;
    /**
     * Kostenstelle 2.
     */
    habenKst2?: string | null;
    /**
     * Installateur, FremdschlÃ¼ssel auf GeschPartner.
     */
    iD_Installateur?: number | null;
    /**
     * Kontrolleur, FremdschlÃ¼ssel auf GeschPartner.
     */
    iD_Kontrolleur?: number | null;
    /**
     * Netzbetreiberin, FremdschlÃ¼ssel auf GeschPartner.
     */
    idWerk?: number | null;
    /**
     * VnbGUID aus EVU-Pack-Datei, wird gesetzt wenn Daten vom VNB abgerufen werden oder ein Formular an ein VNB mit  GUID gesendet wird.
     */
    vnbGUID?: string | null;
    /**
     * Evu-Adress-Plugin-Name von stromlieferndem VNB.
     */
    stromlieferVnb?: string | null;
    /**
     * Werk-Nr. fÃ¼r die Formulare.
     */
    werkNr?: string | null;
    /**
     * Jahr der Werk-Nr. fÃ¼r die Formulare.
     */
    jahr?: number | null;
    /**
     * Datum der Inbetriebnahme.
     */
    datumInbetrieb?: string | null;
    /**
     * Notizen (im Dossier direkt bearbeitbar).
     */
    beschrieb?: string | null;
    /**
     * Auftragsbeschrieb (wird auf Formulare Ã¼bernommen).
     */
    bemerkungen?: string | null;
    /**
     * Referenz-Nummer fÃ¼r externen Datenabgleich/DatenÃ¼bernahme/Datenaustausch.
     */
    referenzNr?: string | null;
    /**
     * CRC32 des importierten Dossiers.
     */
    importCRC?: number | null;
    /**
     * Extern befÃ¼llte Felder, welche nun im Programm gesperrt sind.
     */
    gesperrteFelder?: string | null;
    /**
     * Auftrags-Art, z.B. Bauprojekt, PK, Temp.; FremdschlÃ¼ssel auf AuftragsArten.
     */
    iD_AuftragsArt?: number | null;
    /**
     * Ersteller des Auftrags, 1 = Installateur, 2 = Kontrolleur, 4 = EVU.
     */
    ersteller?: number | null;
    /**
     * true = Dieser Elektro-Auftrag ist erledigt/abgeschlossen.
     */
    erledigt?: boolean;
    /**
     * Die Phasen dieses Elektro-Auftrags.
     */
    phasen?: Array<EAuftragPhaseDTO> | null;
    /**
     * Alle Dokumente im Dokumentpool dieses Auftrages.
     */
    dokumente?: Array<EAuftragDokumentDTO> | null;
}

