/**
 * Next-Gen App API
 * Die REST Web-Schnittstelle zu der Next-Gen App Anwendung
 *
 * The version of the OpenAPI document: v1
 * Contact: info@brunnerinformatik.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FormularKategorieDTO } from './formularKategorieDTO';
import { EmpfaengerKategorieDTO } from './empfaengerKategorieDTO';
import { ELeistungDTO } from './eLeistungDTO';


export interface EAuftragPhaseDTO { 
    guid?: string | null;
    fortschritt?: number;
    status?: number;
    komponente?: string;
    guiData?: string | null;
    /**
     * Die Sammlung aller EmpfÃ¤nger-Kategorien, welche innerhalb dieser Auftragsphase ausgewÃ¤hlt werden kÃ¶nnen.
     */
    empfaengerKategorien?: Array<EmpfaengerKategorieDTO> | null;
    /**
     * Die Sammlung aller Formular-Kategorien, welche innerhalb dieser Auftragsphase erstellt werden kÃ¶nnen.
     */
    formularKategorien?: Array<FormularKategorieDTO> | null;
    /**
     * Alle in dieser Auftragsphase referenzierten Anlagen.
     */
    anlagen?: Array<string> | null;
    /**
     * Alle Leistungen dieser Auftragsphase.
     */
    leistungen?: Array<ELeistungDTO> | null;
}

