/**
 * Next-Gen App API
 * Die REST Web-Schnittstelle zu der Next-Gen App Anwendung
 *
 * The version of the OpenAPI document: v1
 * Contact: info@brunnerinformatik.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Diese Klasse reprÃ¤sentiert ein Data-Transfer-Object fÃ¼r eine Dokumenttyp EntitÃ¤t der Elektro-Sparte.
 */
export interface EDokumentTypDTO { 
    /**
     * Die eindeutige <see cref=\"T:System.Guid\">GUID</see> dieses Dokumenttyps.
     */
    guid?: string | null;
    /**
     * Der Name dieses Dokumententyps.
     */
    name?: string | null;
    /**
     * Eine optionale Beschreibung fÃ¼r diesen Dokumenttypen.
     */
    description?: string | null;
    /**
     * Eine optionale Kategorisierung fÃ¼r diesen Dokumenttypen.
     */
    category?: string | null;
    /**
     * Der MIME-Typ des Dokumenttyps.
     */
    mimeType?: string | null;
    /**
     * Die optionale Standard Erweiterung fÃ¼r Dateinamen dieses Dokumenttyps.
     */
    fileExtension?: string | null;
}

