/**
 * Next-Gen App API
 * Die REST Web-Schnittstelle zu der Next-Gen App Anwendung
 *
 * The version of the OpenAPI document: v1
 * Contact: info@brunnerinformatik.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Diese Klasse reprÃ¤sentiert ein Data-Transfer-Object eines Dokumentattributes fÃ¼r Dokumente aus der Elektro Sparte.
 */
export interface EDokumentAttributDTO { 
    /**
     * Die eindeutige <see cref=\"P:BrunnerInformatik.NextGen.App.ViewModel.EDokumentAttributDTO.Guid\">GUID</see> dieses Dokumentattributes.
     */
    guid: string;
    /**
     * Der eindeutige Bezeichner dieses Dokumentattributes.
     */
    name?: string | null;
    /**
     * Die URL des Schemas fÃ¼r den Wert dieses Dokumentattributes.
     */
    schemaUrl?: string | null;
}

