/**
 * Next-Gen App API
 * Die REST Web-Schnittstelle zu der Next-Gen App Anwendung
 *
 * The version of the OpenAPI document: v1
 * Contact: info@brunnerinformatik.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type EFormularStatus = 0 | 10 | 20 | 30 | 40 | 50 | 70 | 80 | 100 | 120;

export const EFormularStatus = {
    Undefiniert: 0 as EFormularStatus,
    Imported: 10 as EFormularStatus,
    Pending: 20 as EFormularStatus,
    Merged: 30 as EFormularStatus,
    Locked: 40 as EFormularStatus,
    Signed: 50 as EFormularStatus,
    Forwarded: 70 as EFormularStatus,
    ReImported: 80 as EFormularStatus,
    Exported: 100 as EFormularStatus,
    Terminated: 120 as EFormularStatus
};

