/**
 * Next-Gen App API
 * Die REST Web-Schnittstelle zu der Next-Gen App Anwendung
 *
 * The version of the OpenAPI document: v1
 * Contact: info@brunnerinformatik.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EAktionDTO } from './eAktionDTO';


/**
 * Diese Klasse reprÃ¤sentiert ein Data-Transfer-Object fÃ¼r Elektro-Leistungen EntitÃ¤ten.
 */
export interface ELeistungDTO { 
    /**
     * PrimÃ¤rschlÃ¼ssel: DB-Interne ID der Elektro-Leistung.
     */
    id?: number | null;
    /**
     * PrimÃ¤rschlÃ¼ssel: GUID des Mandanten.
     */
    mandant: string;
    /**
     * GUID der Elektro-Leistung.
     */
    guid?: string | null;
    /**
     * Leistungsdefinition, FremdschlÃ¼ssel zu LeistungDef.
     */
    iD_LeistungDef?: number | null;
    /**
     * GUID der Leistungsdefinition.
     */
    guiD_LeistungDef?: string | null;
    /**
     * Die Phase des Auftrags, zu welcher diese Leistung gehÃ¶rt.
     */
    auftragsPhase?: string;
    /**
     * Die Elektro-Anlage auf welche sich diese Leistung bezieht.
     */
    anlage?: string;
    /**
     * Die GUID der EmpfÃ¤ngerkategorie.
     */
    empfaengerKategorie?: string;
    /**
     * Die GUID des EmpfÃ¤ngers dieser Leistung.
     */
    empfaenger?: string;
    /**
     * Elektro-Leistungsnummer.
     */
    leistungsNr?: string | null;
    /**
     * TODO: Feldbeschreibung hinzufÃ¼gen (ELeistungen->Bezeichnung)!
     */
    bezeichnung?: string | null;
    /**
     * TODO: Feldbeschreibung hinzufÃ¼gen (ELeistungen->Kuerzel)!
     */
    kuerzel?: string | null;
    /**
     * NÃ¤here Bezeichnung der Leistung.
     */
    zusatzText?: string | null;
    /**
     * TODO: Feldbeschreibung hinzufÃ¼gen (ELeistungen->Datum)!
     */
    datum?: string | null;
    /**
     * Installateur-Firma, FremdschlÃ¼ssel zu GeschPartner.
     */
    iD_Installateur?: number | null;
    /**
     * Sachbearbeiter der Installateur-Firma.
     */
    instSachb?: string | null;
    /**
     * Kontrolleur-Firma, FremdschlÃ¼ssel zu GeschPartner.
     */
    iD_Kontrolleur?: number | null;
    /**
     * Sachbearbeiter der Kontrolleur-Firma.
     */
    kontrSachb?: string | null;
    /**
     * Sachbearbeiter Technisch, FremdschlÃ¼ssel zu Mitarbeiter.
     */
    iD_SachbTechn?: number | null;
    /**
     * Sachbearbeiter Administrativ, FremdschlÃ¼ssel zu Mitarbeite.
     */
    iD_SachbAdmin?: number | null;
    /**
     * Werk-Nr. fÃ¼r die Formulare.
     */
    werkNr?: string | null;
    /**
     * Jahr der Werk-Nr. fÃ¼r die Formulare.
     */
    jahr?: number | null;
    /**
     * Budgetierter Zeitaufwand.
     */
    budgetZeit?: number | null;
    /**
     * Budgetierter Geldbetrag.
     */
    budgetBetrag?: number | null;
    /**
     * true = Die Leistung ist erledigt/erbracht worden.
     */
    erledigt?: boolean | null;
    /**
     * Datum der Offerte.
     */
    offertDatum?: string | null;
    /**
     * Datum der Auftragserteilung.
     */
    auftragsDatum?: string | null;
    /**
     * Datum und Uhrzeit zu beginn der Kontrolle.
     */
    kontrollDatumVon?: string | null;
    /**
     * Datum und Uhrzeit am Ende der Kontrolle.
     */
    kontrollDatumBis?: string | null;
    /**
     * VSEK Statistikart, FremdschlÃ¼ssel zu VSEKStatistikArt.
     */
    iD_VSEKStatistikArt?: number | null;
    /**
     * true = Es wurden MÃ¤ngel festgestellt.
     */
    maengel?: boolean | null;
    /**
     * Datum der MÃ¤ngelbehebung.
     */
    behebungDatum?: string | null;
    /**
     * Datum der Rechnungsstellung.
     */
    rechnungDatum?: string | null;
    /**
     * Fixierter BriefempfÃ¤nger, FremdschlÃ¼ssel zu Adressen.
     */
    iD_KorrespAdr?: number | null;
    /**
     * Den vom VNB als nÃ¤chstes erwarteter Formular-Typ (Q = SiNa.
     */
    naechstFormTyp?: string | null;
    /**
     * Frist vom VNB des nÃ¤chsten erwarteten Formulars.
     */
    naechstFormFrist?: string | null;
    /**
     * Geplantes Abschlussdatum dieser Elektro-Leistung.
     */
    geplantEndeDatum?: string | null;
    aktionen?: Array<EAktionDTO> | null;
}

