/**
 * Next-Gen App API
 * Die REST Web-Schnittstelle zu der Next-Gen App Anwendung
 *
 * The version of the OpenAPI document: v1
 * Contact: info@brunnerinformatik.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Diese Klasse reprÃ¤sentiert ein Data-Transfer-Object fÃ¼r Elektro-AuftrÃ¤ge EntitÃ¤ten.
 */
export interface EProjektViewDTO { 
    /**
     * PrimÃ¤rschlÃ¼ssel: GUID des Mandanten.
     */
    mandant: string;
    /**
     * AuftragsId
     */
    idEAuftrag: number;
    /**
     * GebÃ¤ude-GUID
     */
    guidEAuftrag: string;
    /**
     * GebÃ¤udesId
     */
    idGebaeude: number;
    /**
     * GebÃ¤ude-GUID
     */
    guidGebaeude: string;
    /**
     * Auftragsnummer vergeben vom Anwender.
     */
    auftragsNr: string;
    /**
     * GebÃ¤udenummer.
     */
    nummer?: string | null;
    /**
     * Stichwort.
     */
    stichwort?: string | null;
    /**
     * Strassenname.
     */
    strasse?: string | null;
    /**
     * Hausnummer / Hausname.
     */
    hausNr?: string | null;
    /**
     * Postleitzahl.
     */
    plz?: string | null;
    /**
     * Ortsname passend zur Postleitzahl.
     */
    postOrt?: string | null;
    anzLeistungen?: number;
    fortschritte?: Array<number> | null;
    idWerk?: number | null;
    vnb_Firma?: string | null;
    vnb_Adresse?: string | null;
    vnb_PLZ?: string | null;
    vnb_Ort?: string | null;
}

