/**
 * Next-Gen App API
 * Die REST Web-Schnittstelle zu der Next-Gen App Anwendung
 *
 * The version of the OpenAPI document: v1
 * Contact: info@brunnerinformatik.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EGeraetDTO } from './eGeraetDTO';
import { EAnlageDTO } from './eAnlageDTO';


/**
 * Diese Klasse reprÃ¤sentiert ein Data-Transfer-Object fÃ¼r GebÃ¤ude EntitÃ¤ten.
 */
export interface GebaeudeDTO { 
    /**
     * PrimÃ¤rschlÃ¼ssel: GUID des Mandanten.
     */
    mandant: string;
    /**
     * GUID des GebÃ¤udes.
     */
    guid?: string | null;
    /**
     * Haupt-GebÃ¤udeart (z.B. Wohnhaus).
     */
    gebaeudeArt1?: string | null;
    /**
     * Neben-GebÃ¤udeart (z.B. Stall).
     */
    gebaeudeArt2?: string | null;
    /**
     * GebÃ¤udenummer.
     */
    nummer?: string | null;
    /**
     * EidgenÃ¶ssischer GebÃ¤ude-Identifikator.
     */
    egid?: number | null;
    /**
     * Das Baujahr dieses GebÃ¤udes.
     */
    baujahr?: number | null;
    /**
     * GebÃ¤udenummer vergeben durch die GebÃ¤udeversicherung.
     */
    assekuranzNr?: string | null;
    /**
     * Enddatum der GÃ¼ltigkeit dieses GebÃ¤udes.
     */
    gueltigBis?: string | null;
    /**
     * Gemeinde.
     */
    gemeinde?: string | null;
    /**
     * Ortschaft / Weiler.
     */
    ortschaft?: string | null;
    /**
     * Strassenname.
     */
    strasse?: string | null;
    /**
     * Hausnummer / Hausname.
     */
    hausNr?: string | null;
    /**
     * Ganzzahliger Anteil der Spalte: \'Hausnummer\' fÃ¼r die Sortierung.
     */
    hausNrSort?: number | null;
    /**
     * Postleitzahl.
     */
    plz?: string | null;
    /**
     * Ortsname passend zur Postleitzahl.
     */
    postOrt?: string | null;
    /**
     * Katasterplannummer.
     */
    katasterplanNr?: string | null;
    /**
     * Planquadrat.
     */
    planQuadrat?: string | null;
    /**
     * Parzellennummer.
     */
    parzelleNr?: string | null;
    /**
     * Geographisches Koordinatensystem (z.B.: GPS, GLONASS).
     */
    geoSystem?: string | null;
    /**
     * Geographische Koordinate: LÃ¤ngengrade
     */
    geoLaenge?: string | null;
    /**
     * Geographische Koordinate: Breitengrade
     */
    geoBreite?: string | null;
    /**
     * Inhaber, FremdschlÃ¼ssel auf \'GeschPartner\'.
     */
    iD_Inhaber?: number | null;
    /**
     * Verwaltung, FremdschlÃ¼ssel auf `GeschPartner`.
     */
    guid_Verwaltung?: string | null;
    /**
     * Inhaber, FremdschlÃ¼ssel auf \'GeschPartner\'.
     */
    guid_Inhaber?: string | null;
    /**
     * Verwaltung, FremdschlÃ¼ssel auf `GeschPartner`.
     */
    iD_Verwaltung?: number | null;
    /**
     * Korrespondenz an: 1 = Inahber; 2 = Verwaltung.
     */
    korrespAn?: number | null;
    /**
     * Referenz-Nummer fÃ¼r externen Datenabgleich/DatenÃ¼bernahme/Datenaustausch.
     */
    referenzNr?: string | null;
    /**
     * Bemerkungen.
     */
    bemerkungen?: string | null;
    /**
     * Einteilung des GebÃ¤udes nach Sektion/Region/Abteilung.
     */
    sektion?: string | null;
    anlagen?: Array<EAnlageDTO> | null;
    geraete?: Array<EGeraetDTO> | null;
}

