/**
 * Next-Gen App API
 * Die REST Web-Schnittstelle zu der Next-Gen App Anwendung
 *
 * The version of the OpenAPI document: v1
 * Contact: info@brunnerinformatik.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface IdentityContextDTO { 
    mandant?: string | null;
    holding?: string | null;
    holdingName?: string | null;
    geschaeftsstelle?: string | null;
    geschaeftsstelleName?: string | null;
    mitarbeiter?: string | null;
    mitarbeiterVorname?: string | null;
    mitarbeiterNachname?: string | null;
    mitarbeiterRolle?: string | null;
}

